FROM osimis/orthanc:22.10.2

USER root
RUN apt-get update && apt-get install -y lua5.1 lua5.1-dev

COPY orthanc_config/orthanc.json /etc/orthanc/orthanc.json
COPY orthanc_scripts/auto_contour_trigger.lua /etc/orthanc/auto_contour_trigger.lua

EXPOSE 8042 4242

ENTRYPOINT ["Orthanc"]
CMD ["/etc/orthanc/orthanc.json"]
