FROM jodogne/orthanc-plugins:latest

# Create lua folder
RUN mkdir -p /etc/orthanc/lua

# Copy dkjson.lua into container
COPY dkjson.lua /etc/orthanc/lua/json.lua

# Copy your Lua script
COPY auto_contour_trigger.lua /etc/orthanc/lua/auto_contour_trigger.lua

# Set permissions (optional)
RUN chmod 644 /etc/orthanc/lua/*.lua

